// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuebS-e3MZFjAaO4gl8MXbf5hN9hk2hP8',
    appId: '1:163837663866:web:5b3a88d139f371789e79c3',
    messagingSenderId: '163837663866',
    projectId: 'ss34-973fc',
    authDomain: 'ss34-973fc.firebaseapp.com',
    storageBucket: 'ss34-973fc.firebasestorage.app',
    measurementId: 'G-XP4C1TH5JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4DSi3C-FK6xc6SrPlyglR5v1ohaCWxh0',
    appId: '1:163837663866:android:0a3e8defff9e0c8e9e79c3',
    messagingSenderId: '163837663866',
    projectId: 'ss34-973fc',
    storageBucket: 'ss34-973fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC86Ez4oslGd5CWsQmjlIxV3ueG25GEqiU',
    appId: '1:163837663866:ios:790d09339d812d4c9e79c3',
    messagingSenderId: '163837663866',
    projectId: 'ss34-973fc',
    storageBucket: 'ss34-973fc.firebasestorage.app',
    iosBundleId: 'com.example.sajaStorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC86Ez4oslGd5CWsQmjlIxV3ueG25GEqiU',
    appId: '1:163837663866:ios:790d09339d812d4c9e79c3',
    messagingSenderId: '163837663866',
    projectId: 'ss34-973fc',
    storageBucket: 'ss34-973fc.firebasestorage.app',
    iosBundleId: 'com.example.sajaStorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuebS-e3MZFjAaO4gl8MXbf5hN9hk2hP8',
    appId: '1:163837663866:web:b2a0f0913f2dd8c69e79c3',
    messagingSenderId: '163837663866',
    projectId: 'ss34-973fc',
    authDomain: 'ss34-973fc.firebaseapp.com',
    storageBucket: 'ss34-973fc.firebasestorage.app',
    measurementId: 'G-3DF092R4ZW',
  );

}